#=======================================================
#
#                  SkyKnock DEV.
#             https://t.me/skyknockdev
#
#========================================================
# Список времени, когда ивент запускается автоматически (формат HH:mm)
event-times:
  - "12:00"
  - "15:00"
  - "18:00"
  - "21:00"

# Команды, которые выполнятся от имени консоли при убийстве босса (можно указать несколько)
rewards:
  - "give %player% diamond 5"
  - "eco give %player% 100"

# Настройки пчел
bee:
  amount: 5
  health: 150.0
  damage: 8.0 # Урон от одного удара пчелы (2.0 = 1 сердечко)
  name: "&6Пчела-Босс"
  # Эффекты, которые накладываются на игрока при ударе.
  # Время указывается в тиках (20 тиков = 1 секунда)
  effects:
    POISON:
      level: 1
      duration: 100
    SLOW:
      level: 2
      duration: 60

# Настройки места появления
spawn:
  world: "world"
  # Если true - спавн всегда по координатам ниже. Если false - в случайных координатах
  static: true
  # Координаты для static: true (могут обновляться командой /bossbea setspawn)
  x: 0.0
  y: 70.0
  z: 0.0
  # Если static: false, пчелы появятся в случайной точке мира в этом радиусе от 0 0
  random-radius: 1000

messages:
  prefix: "&8[&6BossBee&8]"
  start: "&fИвент начался на координатах &e%loc%&f!"
  stop: "&fВсе боссы повержены, ивент окончен."
  reward: "&aВы получили награду за убийство босса!"
  delay: "&fДо следующего ивента: &e%h% ч. %m% мин."